### ISSUE TITLE
알림 주기가 적용이 안되네요 ㅠㅠ

### ISSUE THREAD

**Issue by XxshiftxX** [20chan/NeckAngel#4]
텍스트는 정상 반영되는데 알림 주기가 설정 반영이 안되네요
~허리는 무조건 10초에 한번씩 펴는게 국룰인가요?~

**Comment by XxshiftxX** [comment]
패치 이력이 있었는데 MD에서는 최초버전으로 링크해줘서 몰랐네요
Duplicate of #1

**Comment by 20chan** [comment]
코드보면서 이래서 안됐구나 하고 있었는데 갑자기 이미 고친거였나봄
머지
타이머 런타임에 인터벌 바꾸면 적용 되나봄
